---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - 2.8.18
          - 2.9.25
          - 2.10.4

    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2

      - name: Set up Python3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install testing dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install molecule
          pip install docker
          pip install podman
          python3 -m pip install --user "molecule[podman,lint]"
          python3 -m pip install --user "molecule[docker,lint]"

      - name: Run molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
